pull_request_rules:
  - name: Update scala steward PRs 🤖
    conditions:
      - base=master
    actions:
      update: {}
  - name: Merge scala steward PRs 🤖
    conditions:
      - author=scala-steward
      - check-success=fsclient
      - base=master
    actions:
      merge:
        method: squash
        strict: true